version: '2'
services:
  cli:
    container_name: "copyleaks-cli"
    build:
      context: ./docker
      dockerfile: Dockerfile
    volumes:
     - .:/usr/src/app
#     - ./docker/config/fpm/ini/sessions.ini:/usr/local/etc/php/conf.d/redis_session.ini
#     - ./docker/config/fpm/ini/date.ini:/usr/local/etc/php/conf.d/date.ini
#     - ./docker/config/fpm/ini/memory.ini:/usr/local/etc/php/conf.d/memory.ini
#     - ./docker/config/fpm/ini/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    links:
     - redis
  redis:
    container_name: "copyleaks-redis"
    image: redis:3.2-alpine
    ports:
     - "8713:6379"
    command: redis-server --appendonly yes
    volumes:
      - ./docker/data/redis/:/data